apetavern/grubs

- code/Camera.cs
- code/Player.cs
- code/UI/HudEntity.scss
- code/Utils/Range.cs
- code/Weapons/Weapon.cs
- code/WormController.cs
Custom 2.5D player controller & camera setup (#10):
- A and D to move left/right
- Aim with cursor
- Right click and drag to move camera
- Scroll to zoom in and out
- Space to jump
> Player controller

- code/Game.cs
- code/Pawn/Player.cs
- code/Pawn/Worm.cs
- code/Pawn/WormAnimator.cs
- code/Pawn/WormController.cs
- code/States/BaseState.cs
- code/States/PlayingState.cs
- code/States/StateHandler.cs
- code/States/SubStates/Turn.cs
- code/States/WaitingState.cs
- code/Utils/GameConfig.cs
Closes #12 
This turn system has a lot of the preliminary structure we need to distinguish a player from a worm. Since we still have lots of work to do on top of this, this should be merged in soon so we don't build a lot of debt up on top.
> Add basic turns system

- code/UI/InventoryPanel.Item.cs
- code/UI/InventoryPanel.scss
> Ammo count in weapon selection popup

- .addon
- code/Terrain/MarchingSquares.cs
- code/Terrain/TerrainMap.cs
- code/Terrain/TerrainModel.cs
- code/Terrain/TerrainType.cs
- code/Terrain/TerrainWallModel.cs
- code/Utils/Extensions/TerrainTypeExtension.cs
Basically just doing a quick run over the terrain code and applying code cleanup and inspections to it. One thing I noticed is that a lot of client-only code was also being run on the server side so that has been changed. With that change, the terrain runs much better than it used to. It definitely needs chunking still though.
> Terrain Cleanup

- code/Player/Grub/Controller/GrubController.cs
- code/Player/Grub/Controller/Mechanics/NoclipMechanic.cs
I wrote this in such a way that it is as isolated from the base code as much as possible.
> Add noclip debug command

- code/Player/Grub/Controller/GrubController.cs
- code/Player/Grub/Controller/Mechanics/NoclipMechanic.cs
- code/Player/Grub/Controller/Mechanics/UnstuckMechanic.cs
- code/Player/Grub/Grub.cs
- The only difference is we don't do an early return, which doesn't seem to be an issue unless you have some cases you want me to test @trundler-dev 
- Boomer also does something similar to this
- Noclip code is all self contained now which is nice
Let me know what you think
> Move unstuck to mechanic

- code/Player/Player.cs
- code/UI/GrubsHud.razor
- code/UI/Health/HealthPanel.razor
- code/UI/Health/PlayerHealth.razor
- code/UI/Inventory/InventoryItem.razor
- code/UI/Inventory/InventoryPanel.razor
- code/Utils/Extensions/IEnumerableExtensions.cs
Still have some work to do, we probably need to network a list of the players in the current gamemode
> Add basic player health ui

- code/UI/GrubsHud.razor
- code/UI/TextChat/TextChat.cs
- code/UI/TextChat/TextChat.razor
- code/UI/TextChat/TextChatEntry.razor
Basic text chat ready to be styled, based on the new sandbox text chat
> Add basic text chat

- code/Gamemodes/Modes/FFA/FreeForAll.cs
- code/UI/GrubsHud.razor
- code/UI/TextChat/TextChat.razor
- code/UI/TurnPanel/TurnPanel.razor
> Basic turn panel

- code/Player/Grub/Grub.Death.cs
- code/UI/PlayerInfoPanel/TextChat/TextChat.cs
- code/UI/PlayerInfoPanel/TextChat/TextChatEntry.razor
> Send a basic death message

- code/Gamemodes/Modes/FFA/FreeForAll.cs
- code/GrubsGame.cs
- code/Player/Grub/Grub.cs
- code/Player/Player.cs
- code/Player/Preferences.cs
- code/UI/PlayerInfoPanel/PlayerInfo.razor
Obviously extremely hard coded, only supports up to 8 players. At least lays out the component we will need for the main menu.
> Add color presets

- code/Player/Grub/Controller/GrubController.cs
- code/Player/Grub/Grub.Input.cs
@trundler-dev I tested this out, it seems to work fine, might be worthwhile double checking incase I missed anything
> Fix grub fixing issues

- code/UI/Components/InputGlyph.razor
- code/UI/GrubsHud.razor
- code/UI/InputPanel/InputPanel.razor
They are enabled from the start no matter what, unless we have some way to hide them before the game starts?
> Show some basic input hints

- code/Gamemodes/Modes/FFA/FreeForAll.cs
- code/UI/GameStatePanel/GameStatePanel.cs
- code/UI/GameStatePanel/GameStatePanel.razor
- code/UI/GrubsHud.razor
Only thing is that I don't kick people after a certain time, do we need that?
> Add some playtest result UI

- code/Gamemodes/Gamemode.cs
- code/Gamemodes/Modes/FFA/FreeForAll.cs
- code/GrubsGame.cs
- code/Player/Player.cs
- code/Player/Preferences.cs
- code/UI/GameStatePanel/GameStatePanel.cs
- code/UI/GameStatePanel/GameStatePanel.razor
- code/UI/PlayerInfoPanel/PlayerInfo.razor
- code/UI/PlayerInfoPanel/PlayerInfoPanel.razor
- code/UI/PlayerInfoPanel/TextChat/TextChat.cs
- code/UI/PlayerInfoPanel/TextChat/TextChatEntry.razor
- code/UI/TurnPanel/TurnPanel.razor
- weapons/bazooka.prefab
> General playtest feedback

- code/Gamemodes/Gamemode.cs
- code/Gamemodes/Modes/FFA/FreeForAll.cs
- code/Player/GrubsCamera.cs
- code/Player/Inventory.cs
- code/Player/Player.Input.cs
- code/Player/Player.cs
- code/UI/World/DamageNumber.cs
- code/UI/World/NameTag.cs
- code/Utils/Extensions/EntityExtensions.cs
- code/Weapons/Components/BuildComponent.cs
Seems like the camera component does not want to behave on the client. I think at this point we should just create the `Player()` on connect and reset it accordingly. 
- All components we need now are binded on player
- We had to previously transfer the preferences component onto the player because if the client went null other players couldn't get access to it
Happy to chat in the discord about this
> Fix camera stuttering

- code/Weapons/Components/HitScanComponent.cs
https://github.com/apetavern/sbox-grubs/issues/192
Seemed okay from my testing, might be worth playing around ingame...
> Fix hitscan pushback

- code/Player/GrubsCamera.cs
Fixes: #235 
https://user-images.githubusercontent.com/66768086/236642135-61c603ac-2647-4c71-8e7d-82820f809ee9.mp4
> Clamp camera from entering KillZone.

- code/Terrain/ExplosionHelper.cs
- code/Terrain/Terrain.Modifications.cs
- code/Weapons/Components/HitScanComponent.cs
- materials/environment/sand_a.vmat
- materials/environment/sand_shells.vmat
Just some tweaks I did locally since the main PR.
* Scorch with hitscan weapons too
* Make sand scorching look more like mud for better contrast with the background
https://github.com/apetavern/sbox-grubs/assets/1110904/ddb1d6e5-d67f-4b79-b227-c6d8783cab98
> Scorching tweaks

- code/Terrain/Terrain.Generate.cs
- code/Terrain/Terrain.cs
Also subtract big background box first instead of last
> Nicer terrain generation animation by shuffling edits

- code/Bots/BotBrain.cs
- code/Bots/States/CrateFindingState.cs
- code/Bots/States/PositioningState.cs
- code/Gamemodes/Modes/FFA/FreeForAll.cs
This PR fixes the compile errors from the latest update to the AStar library.
> Fix compile errors for AStar

- code/Pawn/Controller/GrubCharacterController.cs
> Scale landing particles based on velocity

- Code/UI/GameHud/FreeForAllHud.razor.scss
- Code/UI/World/GrubVitals.razor.scss
This PR fixes the nametag ui issues, as well as time translation issues
Before:
After
Before:
After:
> UI translation fixes
